# Generated by Django 3.2.12 on 2022-03-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.user')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('first_name', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=300, null=True)),
            ],
        ),
    ]
